spring.application.name=SistemaReclutamiento
server.port=8080

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/talento_academico?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Lima}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

spring.sql.init.mode=never
server.servlet.session.timeout=30m
