DROP TABLE IF EXISTS entrevistas;
DROP TABLE IF EXISTS postulantes;
DROP TABLE IF EXISTS ofertas_laborales;
DROP TABLE IF EXISTS areas;
DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120),
    email VARCHAR(120),
    password VARCHAR(120),
    telefono VARCHAR(40),
    rol VARCHAR(30),
    activo BOOLEAN
);

CREATE TABLE areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120),
    descripcion VARCHAR(255)
);

CREATE TABLE ofertas_laborales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150),
    descripcion VARCHAR(800),
    vacantes INTEGER,
    area_id BIGINT,
    activa BOOLEAN,
    CONSTRAINT fk_ofertas_area FOREIGN KEY (area_id) REFERENCES areas(id)
);

CREATE TABLE postulantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120),
    email VARCHAR(120),
    telefono VARCHAR(40),
    experiencia VARCHAR(700),
    habilidades VARCHAR(700),
    cv VARCHAR(255),
    fecha_postulacion DATE,
    estado VARCHAR(30),
    oferta_id BIGINT,
    usuario_id BIGINT,
    aprobado BOOLEAN,
    observacion VARCHAR(700),
    CONSTRAINT fk_postulantes_oferta FOREIGN KEY (oferta_id) REFERENCES ofertas_laborales(id),
    CONSTRAINT fk_postulantes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE entrevistas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_entrevista VARCHAR(30),
    fecha DATE,
    hora TIME,
    lugar VARCHAR(150),
    modalidad VARCHAR(60),
    resultado VARCHAR(30),
    observacion VARCHAR(700),
    estado_entrevista VARCHAR(30),
    postulante_id BIGINT,
    CONSTRAINT fk_entrevistas_postulante FOREIGN KEY (postulante_id) REFERENCES postulantes(id)
);
